;JPGIncWinscriptFlag Start shortcutNames
/* This program was written by Joshua Graham joshua.graham@jpgautomation.com
 * www.jpgautomation.com
 * Anyone may use any part of this code for any non-malicious purpose
 * with or without referencing me. There is No Warranty 
 */
;Do not edit this file.
JPGIncShortcuts := "add,"
JPGIncCodeSegments := "autoExecute,recompiler,defaultHotkeys,display,controller,shortcutLauncher,"
;JPGIncWinscriptFlag End shortcutNames